<?php

namespace Database\Seeders;

use App\Models\Klpdi;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class KlpdSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        //
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 14638, 'kode_klpdi' => 'D1', 'kode_provinsi' => 1, 'nama_klpdi' => 'Aceh']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14646, 'kode_klpdi' => 'D10', 'kode_provinsi' => 1, 'nama_klpdi' => 'Kab. Bireuen']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14759, 'kode_klpdi' => 'D100', 'kode_provinsi' => 12, 'nama_klpdi' => 'Kab. Majalengka']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 15018, 'kode_klpdi' => 'D1002', 'kode_provinsi' => 32, 'nama_klpdi' => 'Provinsi Papua Tengah']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 15019, 'kode_klpdi' => 'D1003', 'kode_provinsi' => 32, 'nama_klpdi' => 'Provinsi Papua Selatan']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 16037, 'kode_klpdi' => 'D1004', 'kode_provinsi' => 38, 'nama_klpdi' => 'Provinsi Papua Barat Daya']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 15020, 'kode_klpdi' => 'D1005', 'kode_provinsi' => 32, 'nama_klpdi' => 'Provinsi Papua Pegunungan']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14763, 'kode_klpdi' => 'D101', 'kode_provinsi' => 12, 'nama_klpdi' => 'Kota Bogor']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16007, 'kode_klpdi' => 'D102', 'kode_provinsi' => 12, 'nama_klpdi' => 'Kab. Bandung Barat']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14760, 'kode_klpdi' => 'D103', 'kode_provinsi' => 12, 'nama_klpdi' => 'Kab. Cirebon']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14762, 'kode_klpdi' => 'D104', 'kode_provinsi' => 12, 'nama_klpdi' => 'Kota Sukabumi']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14761, 'kode_klpdi' => 'D105', 'kode_provinsi' => 12, 'nama_klpdi' => 'Kab. Garut']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14757, 'kode_klpdi' => 'D106', 'kode_provinsi' => 12, 'nama_klpdi' => 'Kab. Kuningan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14773, 'kode_klpdi' => 'D107', 'kode_provinsi' => 12, 'nama_klpdi' => 'Kab. Bandung']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14722, 'kode_klpdi' => 'D108', 'kode_provinsi' => 12, 'nama_klpdi' => 'Kab. Bogor']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14766, 'kode_klpdi' => 'D109', 'kode_provinsi' => 12, 'nama_klpdi' => 'Kab. Purwakarta']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14629, 'kode_klpdi' => 'D11', 'kode_provinsi' => 1, 'nama_klpdi' => 'Kab. Nagan Raya']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14756, 'kode_klpdi' => 'D110', 'kode_provinsi' => 12, 'nama_klpdi' => 'Kab. Tasikmalaya']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14775, 'kode_klpdi' => 'D111', 'kode_provinsi' => 12, 'nama_klpdi' => 'Kota Cimahi']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14764, 'kode_klpdi' => 'D112', 'kode_provinsi' => 12, 'nama_klpdi' => 'Kota Cirebon']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14778, 'kode_klpdi' => 'D113', 'kode_provinsi' => 12, 'nama_klpdi' => 'Kota Tasikmalaya']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14770, 'kode_klpdi' => 'D114', 'kode_provinsi' => 12, 'nama_klpdi' => 'Kota Bekasi']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14768, 'kode_klpdi' => 'D115', 'kode_provinsi' => 12, 'nama_klpdi' => 'Kab. Bekasi']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14754, 'kode_klpdi' => 'D116', 'kode_provinsi' => 12, 'nama_klpdi' => 'Kab. Ciamis']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14774, 'kode_klpdi' => 'D117', 'kode_provinsi' => 12, 'nama_klpdi' => 'Kab. Cianjur']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14758, 'kode_klpdi' => 'D118', 'kode_provinsi' => 12, 'nama_klpdi' => 'Kab. Sumedang']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14777, 'kode_klpdi' => 'D119', 'kode_provinsi' => 12, 'nama_klpdi' => 'Kota Banjar']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14645, 'kode_klpdi' => 'D12', 'kode_provinsi' => 1, 'nama_klpdi' => 'Kab. Pidie']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14767, 'kode_klpdi' => 'D120', 'kode_provinsi' => 12, 'nama_klpdi' => 'Kab. Subang']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14771, 'kode_klpdi' => 'D121', 'kode_provinsi' => 12, 'nama_klpdi' => 'Kab. Sukabumi']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 14804, 'kode_klpdi' => 'D122', 'kode_provinsi' => 13, 'nama_klpdi' => 'Provinsi Jawa Tengah']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14800, 'kode_klpdi' => 'D123', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kab. Brebes']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14791, 'kode_klpdi' => 'D124', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kab. Banyumas']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14780, 'kode_klpdi' => 'D125', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kab. Karanganyar']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14783, 'kode_klpdi' => 'D126', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kab. Blora']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14801, 'kode_klpdi' => 'D127', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kota Tegal']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14794, 'kode_klpdi' => 'D128', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kab. Kebumen']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14804, 'kode_klpdi' => 'D129', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kota Semarang']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16000, 'kode_klpdi' => 'D13', 'kode_provinsi' => 1, 'nama_klpdi' => 'Kab. Pidie Jaya']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14795, 'kode_klpdi' => 'D130', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kab. Purworejo']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14789, 'kode_klpdi' => 'D131', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kab. Banjarnegara']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14811, 'kode_klpdi' => 'D132', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kab. Pekalongan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14805, 'kode_klpdi' => 'D133', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kab. Pemalang']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14809, 'kode_klpdi' => 'D134', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kab. Jepara']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14790, 'kode_klpdi' => 'D135', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kab. Cilacap']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14810, 'kode_klpdi' => 'D136', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kab. Batang']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14787, 'kode_klpdi' => 'D137', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kab. Boyolali']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14807, 'kode_klpdi' => 'D138', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kab. Semarang']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14785, 'kode_klpdi' => 'D139', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kab. Sragen']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14634, 'kode_klpdi' => 'D14', 'kode_provinsi' => 1, 'nama_klpdi' => 'Kota Langsa']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14812, 'kode_klpdi' => 'D140', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kab. Temanggung']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14781, 'kode_klpdi' => 'D141', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kab. Klaten']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14799, 'kode_klpdi' => 'D142', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kab. Tegal']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14802, 'kode_klpdi' => 'D143', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kota Pekalongan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14786, 'kode_klpdi' => 'D144', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kab. Grobogan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14808, 'kode_klpdi' => 'D145', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kab. Kudus']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14793, 'kode_klpdi' => 'D146', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kab. Magelang']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14798, 'kode_klpdi' => 'D147', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kota Surakarta']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14803, 'kode_klpdi' => 'D148', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kota Salatiga']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14788, 'kode_klpdi' => 'D149', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kab. Purbalingga']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14643, 'kode_klpdi' => 'D15', 'kode_provinsi' => 1, 'nama_klpdi' => 'Kab. Simeulue']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14782, 'kode_klpdi' => 'D150', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kab. Sukoharjo']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14792, 'kode_klpdi' => 'D151', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kab. Wonosobo']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14797, 'kode_klpdi' => 'D152', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kota Magelang']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14779, 'kode_klpdi' => 'D153', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kab. Wonogiri']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14806, 'kode_klpdi' => 'D154', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kab. Demak']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14813, 'kode_klpdi' => 'D155', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kab. Kendal']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14796, 'kode_klpdi' => 'D156', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kab. Pati']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14784, 'kode_klpdi' => 'D157', 'kode_provinsi' => 13, 'nama_klpdi' => 'Kab. Rembang']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 14847, 'kode_klpdi' => 'D158', 'kode_provinsi' => 15, 'nama_klpdi' => 'Provinsi Jawa Timur']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14836, 'kode_klpdi' => 'D159', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kab. Banyuwangi']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14632, 'kode_klpdi' => 'D16', 'kode_provinsi' => 1, 'nama_klpdi' => 'Kab. Aceh Barat Daya']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14819, 'kode_klpdi' => 'D160', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kab. Sidoarjo']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14850, 'kode_klpdi' => 'D161', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kab. Madiun']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14848, 'kode_klpdi' => 'D162', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kab. Sumenep']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14833, 'kode_klpdi' => 'D163', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kab. Pacitan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14824, 'kode_klpdi' => 'D164', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kab. Jombang']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14853, 'kode_klpdi' => 'D165', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kab. Magetan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14839, 'kode_klpdi' => 'D166', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kab. Malang']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14828, 'kode_klpdi' => 'D167', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kab. Nganjuk']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14844, 'kode_klpdi' => 'D168', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kab. Gresik']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14831, 'kode_klpdi' => 'D169', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kab. Blitar']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14644, 'kode_klpdi' => 'D17', 'kode_provinsi' => 1, 'nama_klpdi' => 'Kab. Aceh Singkil']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14820, 'kode_klpdi' => 'D170', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kab. Mojokerto']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14855, 'kode_klpdi' => 'D171', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kab. Bojonegoro']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14838, 'kode_klpdi' => 'D172', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kab. Jember']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14835, 'kode_klpdi' => 'D173', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kab. Kediri']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14849, 'kode_klpdi' => 'D174', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kab. Lamongan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14856, 'kode_klpdi' => 'D175', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kab. Ngawi']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14822, 'kode_klpdi' => 'D176', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kab. Situbondo']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14846, 'kode_klpdi' => 'D177', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kota Batu']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14827, 'kode_klpdi' => 'D178', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kota Blitar']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14851, 'kode_klpdi' => 'D179', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kota Madiun']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14631, 'kode_klpdi' => 'D18', 'kode_provinsi' => 1, 'nama_klpdi' => 'Kab. Aceh Tamiang']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14825, 'kode_klpdi' => 'D180', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kota Malang']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14847, 'kode_klpdi' => 'D181', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kota Surabaya']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14823, 'kode_klpdi' => 'D182', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kab. Probolinggo']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14840, 'kode_klpdi' => 'D183', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kab. Lumajang']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14852, 'kode_klpdi' => 'D184', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kota Mojokerto']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14821, 'kode_klpdi' => 'D185', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kab. Pasuruan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14842, 'kode_klpdi' => 'D186', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kab. Sampang']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14829, 'kode_klpdi' => 'D187', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kota Kediri']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14826, 'kode_klpdi' => 'D188', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kota Probolinggo']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14854, 'kode_klpdi' => 'D189', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kab. Tuban']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14633, 'kode_klpdi' => 'D19', 'kode_provinsi' => 1, 'nama_klpdi' => 'Kab. Gayo Lues']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14837, 'kode_klpdi' => 'D190', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kab. Bondowoso']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14841, 'kode_klpdi' => 'D191', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kota Pasuruan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14832, 'kode_klpdi' => 'D192', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kab. Trenggalek']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14845, 'kode_klpdi' => 'D193', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kab. Pamekasan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14830, 'kode_klpdi' => 'D194', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kab. Tulungagung']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14843, 'kode_klpdi' => 'D195', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kab. Bangkalan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14834, 'kode_klpdi' => 'D196', 'kode_provinsi' => 15, 'nama_klpdi' => 'Kab. Ponorogo']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 14861, 'kode_klpdi' => 'D197', 'kode_provinsi' => 20, 'nama_klpdi' => 'Provinsi Kalimantan Barat']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14857, 'kode_klpdi' => 'D198', 'kode_provinsi' => 20, 'nama_klpdi' => 'Kab. Sekadau']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14861, 'kode_klpdi' => 'D199', 'kode_provinsi' => 20, 'nama_klpdi' => 'Kota Pontianak']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14638, 'kode_klpdi' => 'D2', 'kode_provinsi' => 1, 'nama_klpdi' => 'Kota Banda Aceh']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 16001, 'kode_klpdi' => 'D20', 'kode_provinsi' => 20, 'nama_klpdi' => 'Kota Subulussalam']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14860, 'kode_klpdi' => 'D200', 'kode_provinsi' => 20, 'nama_klpdi' => 'Kota Singkawang']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14866, 'kode_klpdi' => 'D201', 'kode_provinsi' => 20, 'nama_klpdi' => 'Kab. Ketapang']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16008, 'kode_klpdi' => 'D202', 'kode_provinsi' => 20, 'nama_klpdi' => 'Kab. Kubu Raya']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14867, 'kode_klpdi' => 'D204', 'kode_provinsi' => 20, 'nama_klpdi' => 'Kab. Sanggau']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14863, 'kode_klpdi' => 'D205', 'kode_provinsi' => 20, 'nama_klpdi' => 'Kab. Landak']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14864, 'kode_klpdi' => 'D206', 'kode_provinsi' => 20, 'nama_klpdi' => 'Kab. Bengkayang']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16009, 'kode_klpdi' => 'D207', 'kode_provinsi' => 20, 'nama_klpdi' => 'Kab. Kayong Utara']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14865, 'kode_klpdi' => 'D208', 'kode_provinsi' => 20, 'nama_klpdi' => 'Kab. Sambas']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14858, 'kode_klpdi' => 'D209', 'kode_provinsi' => 20, 'nama_klpdi' => 'Kab. Kapuas Hulu']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14637, 'kode_klpdi' => 'D21', 'kode_provinsi' => 1, 'nama_klpdi' => 'Kab. Bener Meriah']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14862, 'kode_klpdi' => 'D210', 'kode_provinsi' => 20, 'nama_klpdi' => 'Kab. Melawi']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14859, 'kode_klpdi' => 'D211', 'kode_provinsi' => 20, 'nama_klpdi' => 'Kab. Sintang']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 14890, 'kode_klpdi' => 'D212', 'kode_provinsi' => 22, 'nama_klpdi' => 'Provinsi Kalimantan Selatan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14888, 'kode_klpdi' => 'D213', 'kode_provinsi' => 22, 'nama_klpdi' => 'Kab. Banjar']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14890, 'kode_klpdi' => 'D214', 'kode_provinsi' => 22, 'nama_klpdi' => 'Kota Banjarmasin']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14891, 'kode_klpdi' => 'D215', 'kode_provinsi' => 22, 'nama_klpdi' => 'Kab. Balangan']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14895, 'kode_klpdi' => 'D216', 'kode_provinsi' => 22, 'nama_klpdi' => 'Kota Banjarbaru']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14893, 'kode_klpdi' => 'D217', 'kode_provinsi' => 22, 'nama_klpdi' => 'Kab. Hulu Sungai Utara']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14886, 'kode_klpdi' => 'D218', 'kode_provinsi' => 22, 'nama_klpdi' => 'Kab. Tanah Laut']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14894, 'kode_klpdi' => 'D219', 'kode_provinsi' => 22, 'nama_klpdi' => 'Kab. Tabalong']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14642, 'kode_klpdi' => 'D22', 'kode_provinsi' => 1, 'nama_klpdi' => 'Kab. Aceh Selatan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14884, 'kode_klpdi' => 'D220', 'kode_provinsi' => 22, 'nama_klpdi' => 'Kab. Tapin']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14885, 'kode_klpdi' => 'D221', 'kode_provinsi' => 22, 'nama_klpdi' => 'Kab. Hulu Sungai Selatan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14892, 'kode_klpdi' => 'D222', 'kode_provinsi' => 22, 'nama_klpdi' => 'Kab. Tanah Bumbu']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14883, 'kode_klpdi' => 'D223', 'kode_provinsi' => 22, 'nama_klpdi' => 'Kab. Barito Kuala']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14889, 'kode_klpdi' => 'D224', 'kode_provinsi' => 22, 'nama_klpdi' => 'Kab. Hulu Sungai Tengah']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14887, 'kode_klpdi' => 'D225', 'kode_provinsi' => 22, 'nama_klpdi' => 'Kab. Kotabaru']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 14873, 'kode_klpdi' => 'D226', 'kode_provinsi' => 21, 'nama_klpdi' => 'Provinsi Kalimantan Tengah']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14877, 'kode_klpdi' => 'D227', 'kode_provinsi' => 21, 'nama_klpdi' => 'Kab. Kotawaringin Timur']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14878, 'kode_klpdi' => 'D228', 'kode_provinsi' => 21, 'nama_klpdi' => 'Kab. Kotawaringin Barat']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14880, 'kode_klpdi' => 'D229', 'kode_provinsi' => 21, 'nama_klpdi' => 'Kab. Lamandau']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14640, 'kode_klpdi' => 'D23', 'kode_provinsi' => 1, 'nama_klpdi' => 'Kab. Aceh Tenggara']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14871, 'kode_klpdi' => 'D230', 'kode_provinsi' => 21, 'nama_klpdi' => 'Kab. Seruyan']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14873, 'kode_klpdi' => 'D231', 'kode_provinsi' => 21, 'nama_klpdi' => 'Kota Palangkaraya']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14882, 'kode_klpdi' => 'D232', 'kode_provinsi' => 21, 'nama_klpdi' => 'Kab. Barito Utara']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14879, 'kode_klpdi' => 'D233', 'kode_provinsi' => 21, 'nama_klpdi' => 'Kab. Barito Selatan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14875, 'kode_klpdi' => 'D234', 'kode_provinsi' => 21, 'nama_klpdi' => 'Kab. Barito Timur']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14872, 'kode_klpdi' => 'D235', 'kode_provinsi' => 21, 'nama_klpdi' => 'Kab. Gunung Mas']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14870, 'kode_klpdi' => 'D236', 'kode_provinsi' => 21, 'nama_klpdi' => 'Kab. Katingan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16010, 'kode_klpdi' => 'D237', 'kode_provinsi' => 21, 'nama_klpdi' => 'Kab. Sukamara']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14869, 'kode_klpdi' => 'D238', 'kode_provinsi' => 21, 'nama_klpdi' => 'Kab. Pulang Pisau']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14876, 'kode_klpdi' => 'D239', 'kode_provinsi' => 21, 'nama_klpdi' => 'Kab. Kapuas']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14641, 'kode_klpdi' => 'D24', 'kode_provinsi' => 1, 'nama_klpdi' => 'Kab. Aceh Timur']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14874, 'kode_klpdi' => 'D240', 'kode_provinsi' => 21, 'nama_klpdi' => 'Kab. Murung Raya']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 14902, 'kode_klpdi' => 'D241', 'kode_provinsi' => 23, 'nama_klpdi' => 'Provinsi Kalimantan Timur']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14897, 'kode_klpdi' => 'D242', 'kode_provinsi' => 23, 'nama_klpdi' => 'Kab. Berau']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14903, 'kode_klpdi' => 'D243', 'kode_provinsi' => 23, 'nama_klpdi' => 'Kota Samarinda']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14908, 'kode_klpdi' => 'D244', 'kode_provinsi' => 23, 'nama_klpdi' => 'Kab. Penajam Paser Utara']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14904, 'kode_klpdi' => 'D245', 'kode_provinsi' => 23, 'nama_klpdi' => 'Kota Tarakan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14898, 'kode_klpdi' => 'D246', 'kode_provinsi' => 23, 'nama_klpdi' => 'Kab. Kutai Kartanegara']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14899, 'kode_klpdi' => 'D247', 'kode_provinsi' => 23, 'nama_klpdi' => 'Kab. Paser']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14905, 'kode_klpdi' => 'D248', 'kode_provinsi' => 23, 'nama_klpdi' => 'Kab. Bulungan']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14902, 'kode_klpdi' => 'D249', 'kode_provinsi' => 23, 'nama_klpdi' => 'Kota Balikpapan']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 14968, 'kode_klpdi' => 'D25', 'kode_provinsi' => 17, 'nama_klpdi' => 'Provinsi Bali']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14907, 'kode_klpdi' => 'D250', 'kode_provinsi' => 23, 'nama_klpdi' => 'Kab. Nunukan']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14901, 'kode_klpdi' => 'D251', 'kode_provinsi' => 23, 'nama_klpdi' => 'Kota Bontang']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14896, 'kode_klpdi' => 'D252', 'kode_provinsi' => 23, 'nama_klpdi' => 'Kab. Kutai Timur']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14906, 'kode_klpdi' => 'D253', 'kode_provinsi' => 23, 'nama_klpdi' => 'Kab. Malinau']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16011, 'kode_klpdi' => 'D254', 'kode_provinsi' => 23, 'nama_klpdi' => 'Kab. Tana Tidung']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14900, 'kode_klpdi' => 'D255', 'kode_provinsi' => 23, 'nama_klpdi' => 'Kab. Kutai Barat']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 15065, 'kode_klpdi' => 'D256', 'kode_provinsi' => 10, 'nama_klpdi' => 'Provinsi Kepulauan Riau']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 15064, 'kode_klpdi' => 'D257', 'kode_provinsi' => 10, 'nama_klpdi' => 'Kota Batam']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15066, 'kode_klpdi' => 'D258', 'kode_provinsi' => 10, 'nama_klpdi' => 'Kab. Karimun']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 15065, 'kode_klpdi' => 'D259', 'kode_provinsi' => 10, 'nama_klpdi' => 'Kota Tanjung Pinang']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14974, 'kode_klpdi' => 'D26', 'kode_provinsi' => 17, 'nama_klpdi' => 'Kab. Badung']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15068, 'kode_klpdi' => 'D260', 'kode_provinsi' => 10, 'nama_klpdi' => 'Kab. Natuna']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15063, 'kode_klpdi' => 'D261', 'kode_provinsi' => 10, 'nama_klpdi' => 'Kab. Lingga']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16012, 'kode_klpdi' => 'D262', 'kode_provinsi' => 10, 'nama_klpdi' => 'Kab. Bintan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16013, 'kode_klpdi' => 'D263', 'kode_provinsi' => 10, 'nama_klpdi' => 'Kab. Kepulauan Anambas']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 14744, 'kode_klpdi' => 'D264', 'kode_provinsi' => 8, 'nama_klpdi' => 'Provinsi Lampung']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16014, 'kode_klpdi' => 'D265', 'kode_provinsi' => 8, 'nama_klpdi' => 'Kab. Pesawaran']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14741, 'kode_klpdi' => 'D266', 'kode_provinsi' => 8, 'nama_klpdi' => 'Kota Metro']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14742, 'kode_klpdi' => 'D267', 'kode_provinsi' => 8, 'nama_klpdi' => 'Kab. Lampung Selatan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14747, 'kode_klpdi' => 'D268', 'kode_provinsi' => 8, 'nama_klpdi' => 'Kab. Lampung Timur']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14744, 'kode_klpdi' => 'D269', 'kode_provinsi' => 8, 'nama_klpdi' => 'Kota Bandar Lampung']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14968, 'kode_klpdi' => 'D27', 'kode_provinsi' => 17, 'nama_klpdi' => 'Kota Denpasar']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14739, 'kode_klpdi' => 'D270', 'kode_provinsi' => 8, 'nama_klpdi' => 'Kab. Lampung Barat']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14746, 'kode_klpdi' => 'D271', 'kode_provinsi' => 8, 'nama_klpdi' => 'Kab. Lampung Utara']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14740, 'kode_klpdi' => 'D272', 'kode_provinsi' => 8, 'nama_klpdi' => 'Kab. Way Kanan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14745, 'kode_klpdi' => 'D273', 'kode_provinsi' => 8, 'nama_klpdi' => 'Kab. Lampung Tengah']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16015, 'kode_klpdi' => 'D274', 'kode_provinsi' => 8, 'nama_klpdi' => 'Kab. Tulang Bawang Barat']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14743, 'kode_klpdi' => 'D275', 'kode_provinsi' => 8, 'nama_klpdi' => 'Kab. Tulang Bawang']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16016, 'kode_klpdi' => 'D276', 'kode_provinsi' => 8, 'nama_klpdi' => 'Kab. Mesuji']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14738, 'kode_klpdi' => 'D277', 'kode_provinsi' => 8, 'nama_klpdi' => 'Kab. Tanggamus']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16017, 'kode_klpdi' => 'D278', 'kode_provinsi' => 8, 'nama_klpdi' => 'Kab. Pringsewu']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 15002, 'kode_klpdi' => 'D279', 'kode_provinsi' => 30, 'nama_klpdi' => 'Provinsi Maluku']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14972, 'kode_klpdi' => 'D28', 'kode_provinsi' => 17, 'nama_klpdi' => 'Kab. Jembrana']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15006, 'kode_klpdi' => 'D280', 'kode_provinsi' => 30, 'nama_klpdi' => 'Kab. Buru']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 15002, 'kode_klpdi' => 'D281', 'kode_provinsi' => 30, 'nama_klpdi' => 'Kota Ambon']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15004, 'kode_klpdi' => 'D282', 'kode_provinsi' => 30, 'nama_klpdi' => 'Kab. Maluku Tenggara']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15000, 'kode_klpdi' => 'D283', 'kode_provinsi' => 30, 'nama_klpdi' => 'Kab. Seram Bagian Barat']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15005, 'kode_klpdi' => 'D284', 'kode_provinsi' => 30, 'nama_klpdi' => 'Kab. Kepulauan Tanimbar']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 16056, 'kode_klpdi' => 'D285', 'kode_provinsi' => 30, 'nama_klpdi' => 'Kota Tual']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15003, 'kode_klpdi' => 'D286', 'kode_provinsi' => 30, 'nama_klpdi' => 'Kab. Seram Bagian Timur']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15007, 'kode_klpdi' => 'D287', 'kode_provinsi' => 30, 'nama_klpdi' => 'Kab. Maluku Tengah']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15001, 'kode_klpdi' => 'D288', 'kode_provinsi' => 30, 'nama_klpdi' => 'Kab. Kepulauan Aru']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16018, 'kode_klpdi' => 'D289', 'kode_provinsi' => 30, 'nama_klpdi' => 'Kab. Buru Selatan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14967, 'kode_klpdi' => 'D29', 'kode_provinsi' => 17, 'nama_klpdi' => 'Kab. Bangli']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16019, 'kode_klpdi' => 'D290', 'kode_provinsi' => 30, 'nama_klpdi' => 'Kab. Maluku Barat Daya']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 15040, 'kode_klpdi' => 'D291', 'kode_provinsi' => 31, 'nama_klpdi' => 'Provinsi Maluku Utara']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15038, 'kode_klpdi' => 'D292', 'kode_provinsi' => 31, 'nama_klpdi' => 'Kab. Halmahera Utara']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 15040, 'kode_klpdi' => 'D293', 'kode_provinsi' => 31, 'nama_klpdi' => 'Kota Ternate']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15041, 'kode_klpdi' => 'D294', 'kode_provinsi' => 31, 'nama_klpdi' => 'Kab. Halmahera Tengah']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15043, 'kode_klpdi' => 'D295', 'kode_provinsi' => 31, 'nama_klpdi' => 'Kab. Halmahera Selatan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16020, 'kode_klpdi' => 'D296', 'kode_provinsi' => 31, 'nama_klpdi' => 'Kab. Halmahera Barat']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15037, 'kode_klpdi' => 'D297', 'kode_provinsi' => 31, 'nama_klpdi' => 'Kab. Halmahera Timur']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15044, 'kode_klpdi' => 'D298', 'kode_provinsi' => 31, 'nama_klpdi' => 'Kab. Kepulauan Sula']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14635, 'kode_klpdi' => 'D3', 'kode_provinsi' => 1, 'nama_klpdi' => 'Kota Lhokseumawe']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14969, 'kode_klpdi' => 'D30', 'kode_provinsi' => 17, 'nama_klpdi' => 'Kab. Buleleng']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 15039, 'kode_klpdi' => 'D300', 'kode_provinsi' => 31, 'nama_klpdi' => 'Kota Tidore Kepulauan']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 14978, 'kode_klpdi' => 'D301', 'kode_provinsi' => 18, 'nama_klpdi' => 'Provinsi Nusa Tenggara Barat']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14975, 'kode_klpdi' => 'D302', 'kode_provinsi' => 18, 'nama_klpdi' => 'Kab. Sumbawa Barat']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14982, 'kode_klpdi' => 'D303', 'kode_provinsi' => 18, 'nama_klpdi' => 'Kab. Sumbawa']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14980, 'kode_klpdi' => 'D304', 'kode_provinsi' => 18, 'nama_klpdi' => 'Kab. Lombok Tengah']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14983, 'kode_klpdi' => 'D305', 'kode_provinsi' => 18, 'nama_klpdi' => 'Kab. Lombok Timur']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14981, 'kode_klpdi' => 'D307', 'kode_provinsi' => 18, 'nama_klpdi' => 'Kab. Lombok Barat']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16022, 'kode_klpdi' => 'D308', 'kode_provinsi' => 18, 'nama_klpdi' => 'Kab. Lombok Utara']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14978, 'kode_klpdi' => 'D309', 'kode_provinsi' => 18, 'nama_klpdi' => 'Kota Mataram']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14973, 'kode_klpdi' => 'D31', 'kode_provinsi' => 17, 'nama_klpdi' => 'Kab. Gianyar']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14977, 'kode_klpdi' => 'D310', 'kode_provinsi' => 18, 'nama_klpdi' => 'Kota Bima']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14976, 'kode_klpdi' => 'D311', 'kode_provinsi' => 18, 'nama_klpdi' => 'Kab. Bima']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 14992, 'kode_klpdi' => 'D312', 'kode_provinsi' => 19, 'nama_klpdi' => 'Provinsi Nusa Tenggara Timur']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14984, 'kode_klpdi' => 'D313', 'kode_provinsi' => 19, 'nama_klpdi' => 'Kab. Ende']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14994, 'kode_klpdi' => 'D314', 'kode_provinsi' => 19, 'nama_klpdi' => 'Kab. Sumba Barat']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16023, 'kode_klpdi' => 'D315', 'kode_provinsi' => 19, 'nama_klpdi' => 'Kab. Sumba Barat Daya']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14999, 'kode_klpdi' => 'D316', 'kode_provinsi' => 19, 'nama_klpdi' => 'Kab. Belu']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14989, 'kode_klpdi' => 'D317', 'kode_provinsi' => 19, 'nama_klpdi' => 'Kota Kupang']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14998, 'kode_klpdi' => 'D318', 'kode_provinsi' => 19, 'nama_klpdi' => 'Kab. Timor Tengah Utara']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14990, 'kode_klpdi' => 'D319', 'kode_provinsi' => 19, 'nama_klpdi' => 'Kab. Manggarai']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14970, 'kode_klpdi' => 'D32', 'kode_provinsi' => 17, 'nama_klpdi' => 'Kab. Klungkung']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14996, 'kode_klpdi' => 'D320', 'kode_provinsi' => 19, 'nama_klpdi' => 'Kab. Alor']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14988, 'kode_klpdi' => 'D321', 'kode_provinsi' => 19, 'nama_klpdi' => 'Kab. Manggarai Barat']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14992, 'kode_klpdi' => 'D322', 'kode_provinsi' => 19, 'nama_klpdi' => 'Kab. Kupang']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14991, 'kode_klpdi' => 'D323', 'kode_provinsi' => 19, 'nama_klpdi' => 'Kab. Rote Ndao']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14993, 'kode_klpdi' => 'D324', 'kode_provinsi' => 19, 'nama_klpdi' => 'Kab. Timor Tengah Selatan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14985, 'kode_klpdi' => 'D325', 'kode_provinsi' => 19, 'nama_klpdi' => 'Kab. Ngada']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16024, 'kode_klpdi' => 'D326', 'kode_provinsi' => 19, 'nama_klpdi' => 'Kab. Nagekeo']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16025, 'kode_klpdi' => 'D327', 'kode_provinsi' => 19, 'nama_klpdi' => 'Kab. Manggarai Timur']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14987, 'kode_klpdi' => 'D328', 'kode_provinsi' => 19, 'nama_klpdi' => 'Kab. Sikka']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16026, 'kode_klpdi' => 'D329', 'kode_provinsi' => 19, 'nama_klpdi' => 'Kab. Sumba Tengah']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14971, 'kode_klpdi' => 'D33', 'kode_provinsi' => 17, 'nama_klpdi' => 'Kab. Tabanan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14995, 'kode_klpdi' => 'D330', 'kode_provinsi' => 19, 'nama_klpdi' => 'Kab. Sumba Timur']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14986, 'kode_klpdi' => 'D331', 'kode_provinsi' => 19, 'nama_klpdi' => 'Kab. Flores Timur']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14997, 'kode_klpdi' => 'D332', 'kode_provinsi' => 19, 'nama_klpdi' => 'Kab. Lembata']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16027, 'kode_klpdi' => 'D333', 'kode_provinsi' => 19, 'nama_klpdi' => 'Kab. Sabu Raijua']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 15031, 'kode_klpdi' => 'D334', 'kode_provinsi' => 32, 'nama_klpdi' => 'Provinsi Papua']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15019, 'kode_klpdi' => 'D335', 'kode_provinsi' => 32, 'nama_klpdi' => 'Kab. Merauke']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15015, 'kode_klpdi' => 'D336', 'kode_provinsi' => 32, 'nama_klpdi' => 'Kab. Asmat']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15017, 'kode_klpdi' => 'D337', 'kode_provinsi' => 32, 'nama_klpdi' => 'Kab. Jayapura']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15033, 'kode_klpdi' => 'D338', 'kode_provinsi' => 32, 'nama_klpdi' => 'Kab. Keerom']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15012, 'kode_klpdi' => 'D339', 'kode_provinsi' => 32, 'nama_klpdi' => 'Kab. Mappi']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14966, 'kode_klpdi' => 'D34', 'kode_provinsi' => 17, 'nama_klpdi' => 'Kab. Karangasem']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15008, 'kode_klpdi' => 'D340', 'kode_provinsi' => 32, 'nama_klpdi' => 'Kab. Mimika']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15018, 'kode_klpdi' => 'D341', 'kode_provinsi' => 32, 'nama_klpdi' => 'Kab. Nabire']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15011, 'kode_klpdi' => 'D342', 'kode_provinsi' => 32, 'nama_klpdi' => 'Kab. Puncak Jaya']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 15031, 'kode_klpdi' => 'D343', 'kode_provinsi' => 32, 'nama_klpdi' => 'Kota Jayapura']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15023, 'kode_klpdi' => 'D344', 'kode_provinsi' => 32, 'nama_klpdi' => 'Kab. Biak Numfor']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15009, 'kode_klpdi' => 'D345', 'kode_provinsi' => 32, 'nama_klpdi' => 'Kab. Boven Digoel']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16028, 'kode_klpdi' => 'D346', 'kode_provinsi' => 32, 'nama_klpdi' => 'Kab. Dogiyai']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15020, 'kode_klpdi' => 'D347', 'kode_provinsi' => 32, 'nama_klpdi' => 'Kab. Jayawijaya']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16029, 'kode_klpdi' => 'D348', 'kode_provinsi' => 32, 'nama_klpdi' => 'Kab. Kepulauan Yapen']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16030, 'kode_klpdi' => 'D349', 'kode_provinsi' => 32, 'nama_klpdi' => 'Kab. Lanny Jaya']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 15058, 'kode_klpdi' => 'D35', 'kode_provinsi' => 9, 'nama_klpdi' => 'Provinsi Bangka Belitung']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16031, 'kode_klpdi' => 'D350', 'kode_provinsi' => 32, 'nama_klpdi' => 'Kab. Mamberamo Raya']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16032, 'kode_klpdi' => 'D351', 'kode_provinsi' => 32, 'nama_klpdi' => 'Kab. Mamberamo Tengah']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15010, 'kode_klpdi' => 'D353', 'kode_provinsi' => 32, 'nama_klpdi' => 'Kab. Paniai']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15013, 'kode_klpdi' => 'D354', 'kode_provinsi' => 32, 'nama_klpdi' => 'Kab. Pegunungan Bintang']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16034, 'kode_klpdi' => 'D355', 'kode_provinsi' => 32, 'nama_klpdi' => 'Kab. Puncak']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15026, 'kode_klpdi' => 'D356', 'kode_provinsi' => 32, 'nama_klpdi' => 'Kab. Sarmi']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15029, 'kode_klpdi' => 'D357', 'kode_provinsi' => 32, 'nama_klpdi' => 'Kab. Supiori']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15014, 'kode_klpdi' => 'D358', 'kode_provinsi' => 32, 'nama_klpdi' => 'Kab. Tolikara']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15027, 'kode_klpdi' => 'D359', 'kode_provinsi' => 32, 'nama_klpdi' => 'Kab. Waropen']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15060, 'kode_klpdi' => 'D36', 'kode_provinsi' => 9, 'nama_klpdi' => 'Kab. Bangka']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15016, 'kode_klpdi' => 'D360', 'kode_provinsi' => 32, 'nama_klpdi' => 'Kab. Yahukimo']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16035, 'kode_klpdi' => 'D361', 'kode_provinsi' => 32, 'nama_klpdi' => 'Kab. Yalimo']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16057, 'kode_klpdi' => 'D362', 'kode_provinsi' => 32, 'nama_klpdi' => 'Kab. Deiyai']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16058, 'kode_klpdi' => 'D363', 'kode_provinsi' => 32, 'nama_klpdi' => 'Kab. Intan Jaya']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 15025, 'kode_klpdi' => 'D364', 'kode_provinsi' => 33, 'nama_klpdi' => 'Provinsi Papua Barat']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15025, 'kode_klpdi' => 'D365', 'kode_provinsi' => 33, 'nama_klpdi' => 'Kab. Manokwari']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 15030, 'kode_klpdi' => 'D366', 'kode_provinsi' => 33, 'nama_klpdi' => 'Kota Sorong']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15021, 'kode_klpdi' => 'D367', 'kode_provinsi' => 33, 'nama_klpdi' => 'Kab. Fak Fak']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15032, 'kode_klpdi' => 'D368', 'kode_provinsi' => 33, 'nama_klpdi' => 'Kab. Kaimana']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15036, 'kode_klpdi' => 'D369', 'kode_provinsi' => 33, 'nama_klpdi' => 'Kab. Raja Ampat']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15059, 'kode_klpdi' => 'D37', 'kode_provinsi' => 9, 'nama_klpdi' => 'Kab. Bangka Tengah']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15024, 'kode_klpdi' => 'D370', 'kode_provinsi' => 33, 'nama_klpdi' => 'Kab. Sorong']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15034, 'kode_klpdi' => 'D371', 'kode_provinsi' => 33, 'nama_klpdi' => 'Kab. Sorong Selatan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15035, 'kode_klpdi' => 'D372', 'kode_provinsi' => 33, 'nama_klpdi' => 'Kab. Teluk Bintuni']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16036, 'kode_klpdi' => 'D373', 'kode_provinsi' => 33, 'nama_klpdi' => 'Kab. Tambrauw']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16037, 'kode_klpdi' => 'D374', 'kode_provinsi' => 33, 'nama_klpdi' => 'Kab. Maybrat']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15028, 'kode_klpdi' => 'D375', 'kode_provinsi' => 33, 'nama_klpdi' => 'Kab. Teluk Wondama']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 14700, 'kode_klpdi' => 'D376', 'kode_provinsi' => 4, 'nama_klpdi' => 'Provinsi Riau']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14700, 'kode_klpdi' => 'D377', 'kode_provinsi' => 4, 'nama_klpdi' => 'Kota Pekanbaru']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14703, 'kode_klpdi' => 'D378', 'kode_provinsi' => 4, 'nama_klpdi' => 'Kab. Kuantan Singingi']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14702, 'kode_klpdi' => 'D379', 'kode_provinsi' => 4, 'nama_klpdi' => 'Kab. Indragiri Hilir']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 15058, 'kode_klpdi' => 'D38', 'kode_provinsi' => 9, 'nama_klpdi' => 'Kota Pangkal Pinang']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14694, 'kode_klpdi' => 'D380', 'kode_provinsi' => 4, 'nama_klpdi' => 'Kab. Kampar']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14698, 'kode_klpdi' => 'D381', 'kode_provinsi' => 4, 'nama_klpdi' => 'Kab. Bengkalis']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14701, 'kode_klpdi' => 'D382', 'kode_provinsi' => 4, 'nama_klpdi' => 'Kab. Pelalawan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14697, 'kode_klpdi' => 'D383', 'kode_provinsi' => 4, 'nama_klpdi' => 'Kab. Rokan Hulu']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14695, 'kode_klpdi' => 'D384', 'kode_provinsi' => 4, 'nama_klpdi' => 'Kab. Siak']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14696, 'kode_klpdi' => 'D385', 'kode_provinsi' => 4, 'nama_klpdi' => 'Kota Dumai']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16038, 'kode_klpdi' => 'D386', 'kode_provinsi' => 4, 'nama_klpdi' => 'Kab. Kepulauan Meranti']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14699, 'kode_klpdi' => 'D387', 'kode_provinsi' => 4, 'nama_klpdi' => 'Kab. Rokan Hilir']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14704, 'kode_klpdi' => 'D388', 'kode_provinsi' => 4, 'nama_klpdi' => 'Kab. Indragiri Hulu']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 14948, 'kode_klpdi' => 'D389', 'kode_provinsi' => 29, 'nama_klpdi' => 'Provinsi Sulawesi Barat']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15062, 'kode_klpdi' => 'D39', 'kode_provinsi' => 9, 'nama_klpdi' => 'Kab. Bangka Selatan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14948, 'kode_klpdi' => 'D390', 'kode_provinsi' => 29, 'nama_klpdi' => 'Kab. Mamuju']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14954, 'kode_klpdi' => 'D391', 'kode_provinsi' => 29, 'nama_klpdi' => 'Kab. Polewali Mandar']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14953, 'kode_klpdi' => 'D392', 'kode_provinsi' => 29, 'nama_klpdi' => 'Kab. Majene']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 268939, 'kode_klpdi' => 'D393', 'kode_provinsi' => 29, 'nama_klpdi' => 'Kab. Pasangkayu']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14942, 'kode_klpdi' => 'D394', 'kode_provinsi' => 29, 'nama_klpdi' => 'Kab. Mamasa']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 14947, 'kode_klpdi' => 'D395', 'kode_provinsi' => 26, 'nama_klpdi' => 'Provinsi Sulawesi Selatan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14943, 'kode_klpdi' => 'D396', 'kode_provinsi' => 26, 'nama_klpdi' => 'Kab. Luwu Utara']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14929, 'kode_klpdi' => 'D397', 'kode_provinsi' => 26, 'nama_klpdi' => 'Kab. Maros']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14947, 'kode_klpdi' => 'D398', 'kode_provinsi' => 26, 'nama_klpdi' => 'Kota Makassar']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14949, 'kode_klpdi' => 'D399', 'kode_provinsi' => 26, 'nama_klpdi' => 'Kab. Enrekang']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14639, 'kode_klpdi' => 'D4', 'kode_provinsi' => 1, 'nama_klpdi' => 'Kab. Aceh Utara']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15061, 'kode_klpdi' => 'D40', 'kode_provinsi' => 9, 'nama_klpdi' => 'Kab. Belitung']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14950, 'kode_klpdi' => 'D400', 'kode_provinsi' => 26, 'nama_klpdi' => 'Kab. Pinrang']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14930, 'kode_klpdi' => 'D401', 'kode_provinsi' => 26, 'nama_klpdi' => 'Kab. Sinjai']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14945, 'kode_klpdi' => 'D402', 'kode_provinsi' => 26, 'nama_klpdi' => 'Kota Palopo']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14946, 'kode_klpdi' => 'D403', 'kode_provinsi' => 26, 'nama_klpdi' => 'Kota Pare Pare']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14934, 'kode_klpdi' => 'D404', 'kode_provinsi' => 26, 'nama_klpdi' => 'Kab. Bantaeng']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14928, 'kode_klpdi' => 'D405', 'kode_provinsi' => 26, 'nama_klpdi' => 'Kab. Pangkajene Kepulauan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14951, 'kode_klpdi' => 'D406', 'kode_provinsi' => 26, 'nama_klpdi' => 'Kab. Sidenreng Rappang']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14952, 'kode_klpdi' => 'D407', 'kode_provinsi' => 26, 'nama_klpdi' => 'Kab. Luwu']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14944, 'kode_klpdi' => 'D408', 'kode_provinsi' => 26, 'nama_klpdi' => 'Kab. Luwu Timur']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14937, 'kode_klpdi' => 'D409', 'kode_provinsi' => 26, 'nama_klpdi' => 'Kab. Gowa']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15057, 'kode_klpdi' => 'D41', 'kode_provinsi' => 9, 'nama_klpdi' => 'Kab. Belitung Timur']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14932, 'kode_klpdi' => 'D410', 'kode_provinsi' => 26, 'nama_klpdi' => 'Kab. Bone']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14935, 'kode_klpdi' => 'D411', 'kode_provinsi' => 26, 'nama_klpdi' => 'Kab. Bulukumba']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14936, 'kode_klpdi' => 'D412', 'kode_provinsi' => 26, 'nama_klpdi' => 'Kab. Kepulauan Selayar']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14938, 'kode_klpdi' => 'D413', 'kode_provinsi' => 26, 'nama_klpdi' => 'Kab. Takalar']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14931, 'kode_klpdi' => 'D414', 'kode_provinsi' => 26, 'nama_klpdi' => 'Kab. Soppeng']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14940, 'kode_klpdi' => 'D415', 'kode_provinsi' => 26, 'nama_klpdi' => 'Kab. Wajo']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16039, 'kode_klpdi' => 'D416', 'kode_provinsi' => 26, 'nama_klpdi' => 'Kab. Toraja Utara']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14933, 'kode_klpdi' => 'D417', 'kode_provinsi' => 26, 'nama_klpdi' => 'Kab. Barru']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14939, 'kode_klpdi' => 'D418', 'kode_provinsi' => 26, 'nama_klpdi' => 'Kab. Jeneponto']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14955, 'kode_klpdi' => 'D419', 'kode_provinsi' => 26, 'nama_klpdi' => 'Kab. Tana Toraja']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15056, 'kode_klpdi' => 'D42', 'kode_provinsi' => 9, 'nama_klpdi' => 'Kab. Bangka Barat']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 14920, 'kode_klpdi' => 'D421', 'kode_provinsi' => 25, 'nama_klpdi' => 'Provinsi Sulawesi Tengah']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14923, 'kode_klpdi' => 'D422', 'kode_provinsi' => 25, 'nama_klpdi' => 'Kab. Donggala']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14921, 'kode_klpdi' => 'D423', 'kode_provinsi' => 25, 'nama_klpdi' => 'Kab. Parigi Moutong']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14922, 'kode_klpdi' => 'D424', 'kode_provinsi' => 25, 'nama_klpdi' => 'Kab. Tojo Una Una']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14920, 'kode_klpdi' => 'D425', 'kode_provinsi' => 25, 'nama_klpdi' => 'Kota Palu']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14919, 'kode_klpdi' => 'D426', 'kode_provinsi' => 25, 'nama_klpdi' => 'Kab. Morowali']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14926, 'kode_klpdi' => 'D427', 'kode_provinsi' => 25, 'nama_klpdi' => 'Kab. Banggai']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14924, 'kode_klpdi' => 'D428', 'kode_provinsi' => 25, 'nama_klpdi' => 'Kab. Poso']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14918, 'kode_klpdi' => 'D429', 'kode_provinsi' => 25, 'nama_klpdi' => 'Kab. Buol']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 15047, 'kode_klpdi' => 'D43', 'kode_provinsi' => 16, 'nama_klpdi' => 'Provinsi Banten']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14925, 'kode_klpdi' => 'D430', 'kode_provinsi' => 25, 'nama_klpdi' => 'Kab. Toli Toli']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16040, 'kode_klpdi' => 'D431', 'kode_provinsi' => 25, 'nama_klpdi' => 'Kab. Sigi']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14927, 'kode_klpdi' => 'D432', 'kode_provinsi' => 25, 'nama_klpdi' => 'Kab. Banggai Kepulauan']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 14960, 'kode_klpdi' => 'D433', 'kode_provinsi' => 27, 'nama_klpdi' => 'Provinsi Sulawesi Tenggara']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14960, 'kode_klpdi' => 'D434', 'kode_provinsi' => 27, 'nama_klpdi' => 'Kota Kendari']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14962, 'kode_klpdi' => 'D435', 'kode_provinsi' => 27, 'nama_klpdi' => 'Kab. Buton']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14959, 'kode_klpdi' => 'D436', 'kode_provinsi' => 27, 'nama_klpdi' => 'Kota Bau Bau']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16041, 'kode_klpdi' => 'D437', 'kode_provinsi' => 27, 'nama_klpdi' => 'Kab. Buton Utara']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14964, 'kode_klpdi' => 'D438', 'kode_provinsi' => 27, 'nama_klpdi' => 'Kab. Konawe Selatan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16042, 'kode_klpdi' => 'D439', 'kode_provinsi' => 27, 'nama_klpdi' => 'Kab. Konawe Utara']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 15046, 'kode_klpdi' => 'D44', 'kode_provinsi' => 16, 'nama_klpdi' => 'Kota Tangerang']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14956, 'kode_klpdi' => 'D440', 'kode_provinsi' => 27, 'nama_klpdi' => 'Kab. Wakatobi']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14957, 'kode_klpdi' => 'D441', 'kode_provinsi' => 27, 'nama_klpdi' => 'Kab. Bombana']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14958, 'kode_klpdi' => 'D442', 'kode_provinsi' => 27, 'nama_klpdi' => 'Kab. Kolaka Utara']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14961, 'kode_klpdi' => 'D443', 'kode_provinsi' => 27, 'nama_klpdi' => 'Kab. Muna']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14965, 'kode_klpdi' => 'D444', 'kode_provinsi' => 27, 'nama_klpdi' => 'Kab. Kolaka']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16043, 'kode_klpdi' => 'D445', 'kode_provinsi' => 27, 'nama_klpdi' => 'Kab. Konawe']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 14914, 'kode_klpdi' => 'D446', 'kode_provinsi' => 24, 'nama_klpdi' => 'Provinsi Sulawesi Utara']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16044, 'kode_klpdi' => 'D447', 'kode_provinsi' => 24, 'nama_klpdi' => 'Kab. Kep. Siau Tagulandang Biaro']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14909, 'kode_klpdi' => 'D448', 'kode_provinsi' => 24, 'nama_klpdi' => 'Kab. Minahasa Utara']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 16045, 'kode_klpdi' => 'D449', 'kode_provinsi' => 24, 'nama_klpdi' => 'Kota Kotamobagu']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15049, 'kode_klpdi' => 'D45', 'kode_provinsi' => 16, 'nama_klpdi' => 'Kab. Lebak']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14912, 'kode_klpdi' => 'D450', 'kode_provinsi' => 24, 'nama_klpdi' => 'Kota Tomohon']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16046, 'kode_klpdi' => 'D451', 'kode_provinsi' => 24, 'nama_klpdi' => 'Kab. Minahasa Tenggara']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14917, 'kode_klpdi' => 'D453', 'kode_provinsi' => 24, 'nama_klpdi' => 'Kab. Bolaang Mongondow']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16047, 'kode_klpdi' => 'D454', 'kode_provinsi' => 24, 'nama_klpdi' => 'Kab. Bolaang Mongondow Timur']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16048, 'kode_klpdi' => 'D455', 'kode_provinsi' => 24, 'nama_klpdi' => 'Kab. Bolaang Mongondow Utara']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14914, 'kode_klpdi' => 'D456', 'kode_provinsi' => 24, 'nama_klpdi' => 'Kota Manado']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14916, 'kode_klpdi' => 'D457', 'kode_provinsi' => 24, 'nama_klpdi' => 'Kab. Kepulauan Talaud']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14915, 'kode_klpdi' => 'D458', 'kode_provinsi' => 24, 'nama_klpdi' => 'Kab. Kepulauan Sangihe']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14910, 'kode_klpdi' => 'D459', 'kode_provinsi' => 24, 'nama_klpdi' => 'Kab. Minahasa Selatan']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 16002, 'kode_klpdi' => 'D46', 'kode_provinsi' => 16, 'nama_klpdi' => 'Kota Serang']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14913, 'kode_klpdi' => 'D460', 'kode_provinsi' => 24, 'nama_klpdi' => 'Kota Bitung']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14911, 'kode_klpdi' => 'D461', 'kode_provinsi' => 24, 'nama_klpdi' => 'Kab. Minahasa']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 14675, 'kode_klpdi' => 'D462', 'kode_provinsi' => 3, 'nama_klpdi' => 'Provinsi Sumatera Barat']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14686, 'kode_klpdi' => 'D463', 'kode_provinsi' => 3, 'nama_klpdi' => 'Kab. Sijunjung']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14688, 'kode_klpdi' => 'D464', 'kode_provinsi' => 3, 'nama_klpdi' => 'Kab. Pesisir Selatan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14689, 'kode_klpdi' => 'D465', 'kode_provinsi' => 3, 'nama_klpdi' => 'Kab. Tanah Datar']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14677, 'kode_klpdi' => 'D466', 'kode_provinsi' => 3, 'nama_klpdi' => 'Kab. Dharmasraya']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14691, 'kode_klpdi' => 'D467', 'kode_provinsi' => 3, 'nama_klpdi' => 'Kab. Pasaman']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14676, 'kode_klpdi' => 'D468', 'kode_provinsi' => 3, 'nama_klpdi' => 'Kota Sawahlunto']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14679, 'kode_klpdi' => 'D469', 'kode_provinsi' => 3, 'nama_klpdi' => 'Kota Padang Panjang']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 16003, 'kode_klpdi' => 'D47', 'kode_provinsi' => 16, 'nama_klpdi' => 'Kota Tangerang Selatan']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14683, 'kode_klpdi' => 'D470', 'kode_provinsi' => 3, 'nama_klpdi' => 'Kota Payakumbuh']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14675, 'kode_klpdi' => 'D471', 'kode_provinsi' => 3, 'nama_klpdi' => 'Kota Padang']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14693, 'kode_klpdi' => 'D472', 'kode_provinsi' => 3, 'nama_klpdi' => 'Kab. Agam']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14692, 'kode_klpdi' => 'D473', 'kode_provinsi' => 3, 'nama_klpdi' => 'Kab. Padang Pariaman']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14681, 'kode_klpdi' => 'D474', 'kode_provinsi' => 3, 'nama_klpdi' => 'Kota Solok']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14685, 'kode_klpdi' => 'D475', 'kode_provinsi' => 3, 'nama_klpdi' => 'Kab. Solok']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14690, 'kode_klpdi' => 'D476', 'kode_provinsi' => 3, 'nama_klpdi' => 'Kab. Lima Puluh Kota']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14678, 'kode_klpdi' => 'D477', 'kode_provinsi' => 3, 'nama_klpdi' => 'Kab. Pasaman Barat']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14684, 'kode_klpdi' => 'D478', 'kode_provinsi' => 3, 'nama_klpdi' => 'Kab. Solok Selatan']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14682, 'kode_klpdi' => 'D479', 'kode_provinsi' => 3, 'nama_klpdi' => 'Kota Bukittinggi']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15045, 'kode_klpdi' => 'D48', 'kode_provinsi' => 16, 'nama_klpdi' => 'Kab. Serang']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14680, 'kode_klpdi' => 'D480', 'kode_provinsi' => 3, 'nama_klpdi' => 'Kota Pariaman']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14687, 'kode_klpdi' => 'D481', 'kode_provinsi' => 3, 'nama_klpdi' => 'Kab. Kepulauan Mentawai']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 14716, 'kode_klpdi' => 'D482', 'kode_provinsi' => 6, 'nama_klpdi' => 'Provinsi Sumatera Selatan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14720, 'kode_klpdi' => 'D483', 'kode_provinsi' => 6, 'nama_klpdi' => 'Kab. Banyuasin']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14718, 'kode_klpdi' => 'D484', 'kode_provinsi' => 6, 'nama_klpdi' => 'Kota Pagar Alam']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14724, 'kode_klpdi' => 'D485', 'kode_provinsi' => 6, 'nama_klpdi' => 'Kab. Muara Enim']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14716, 'kode_klpdi' => 'D486', 'kode_provinsi' => 6, 'nama_klpdi' => 'Kota Palembang']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14715, 'kode_klpdi' => 'D487', 'kode_provinsi' => 6, 'nama_klpdi' => 'Kota Prabumulih']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14721, 'kode_klpdi' => 'D488', 'kode_provinsi' => 6, 'nama_klpdi' => 'Kab. Musi Banyuasin']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14725, 'kode_klpdi' => 'D489', 'kode_provinsi' => 6, 'nama_klpdi' => 'Kab. Ogan Komering Ilir']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 15047, 'kode_klpdi' => 'D49', 'kode_provinsi' => 16, 'nama_klpdi' => 'Kota Cilegon']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14717, 'kode_klpdi' => 'D490', 'kode_provinsi' => 6, 'nama_klpdi' => 'Kota Lubuk Linggau']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16049, 'kode_klpdi' => 'D491', 'kode_provinsi' => 6, 'nama_klpdi' => 'Kab. Empat Lawang']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14726, 'kode_klpdi' => 'D492', 'kode_provinsi' => 6, 'nama_klpdi' => 'Kab. Musi Rawas']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14723, 'kode_klpdi' => 'D493', 'kode_provinsi' => 6, 'nama_klpdi' => 'Kab. Ogan Komering Ulu Selatan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14722, 'kode_klpdi' => 'D494', 'kode_provinsi' => 6, 'nama_klpdi' => 'Kab. Ogan Komering Ulu Timur']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14728, 'kode_klpdi' => 'D495', 'kode_provinsi' => 6, 'nama_klpdi' => 'Kab. Ogan Komering Ulu']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14719, 'kode_klpdi' => 'D496', 'kode_provinsi' => 6, 'nama_klpdi' => 'Kab. Ogan Ilir']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14727, 'kode_klpdi' => 'D497', 'kode_provinsi' => 6, 'nama_klpdi' => 'Kab. Lahat']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 14666, 'kode_klpdi' => 'D498', 'kode_provinsi' => 2, 'nama_klpdi' => 'Provinsi Sumatera Utara']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14653, 'kode_klpdi' => 'D499', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kab. Labuhanbatu']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14649, 'kode_klpdi' => 'D5', 'kode_provinsi' => 1, 'nama_klpdi' => 'Kab. Aceh Barat']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15050, 'kode_klpdi' => 'D50', 'kode_provinsi' => 16, 'nama_klpdi' => 'Kab. Tangerang']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14651, 'kode_klpdi' => 'D500', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kab. Tapanuli Utara']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14659, 'kode_klpdi' => 'D501', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kota Tanjung Balai']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14666, 'kode_klpdi' => 'D502', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kota Medan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14652, 'kode_klpdi' => 'D503', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kab. Asahan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16050, 'kode_klpdi' => 'D504', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kab. Batu Bara']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14669, 'kode_klpdi' => 'D505', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kab. Dairi']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14667, 'kode_klpdi' => 'D506', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kab. Deli Serdang']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14674, 'kode_klpdi' => 'D507', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kab. Humbang Hasundutan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16051, 'kode_klpdi' => 'D508', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kab. Labuhanbatu Selatan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14654, 'kode_klpdi' => 'D509', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kab. Mandailing Natal']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15048, 'kode_klpdi' => 'D51', 'kode_provinsi' => 16, 'nama_klpdi' => 'Kab. Pandeglang']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14673, 'kode_klpdi' => 'D510', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kab. Nias Selatan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16052, 'kode_klpdi' => 'D511', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kab. Padang Lawas']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14671, 'kode_klpdi' => 'D512', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kab. Pakpak Bharat']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14672, 'kode_klpdi' => 'D513', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kab. Samosir']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14664, 'kode_klpdi' => 'D514', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kota Padangsidimpuan']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14660, 'kode_klpdi' => 'D515', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kota Pematangsiantar']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14665, 'kode_klpdi' => 'D516', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kota Tebing Tinggi']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14663, 'kode_klpdi' => 'D517', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kota Binjai']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14661, 'kode_klpdi' => 'D518', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kab. Serdang Bedagai']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14668, 'kode_klpdi' => 'D519', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kab. Langkat']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 14737, 'kode_klpdi' => 'D52', 'kode_provinsi' => 7, 'nama_klpdi' => 'Provinsi Bengkulu']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14650, 'kode_klpdi' => 'D520', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kab. Toba']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14670, 'kode_klpdi' => 'D521', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kab. Karo']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14658, 'kode_klpdi' => 'D522', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kab. Simalungun']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16059, 'kode_klpdi' => 'D523', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kab. Nias Barat']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14656, 'kode_klpdi' => 'D524', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kab. Tapanuli Tengah']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16053, 'kode_klpdi' => 'D525', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kab. Labuhanbatu Utara']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 16060, 'kode_klpdi' => 'D526', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kota Gunungsitoli']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14655, 'kode_klpdi' => 'D527', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kab. Nias']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16054, 'kode_klpdi' => 'D528', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kab. Nias Utara']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14657, 'kode_klpdi' => 'D529', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kab. Tapanuli Selatan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14733, 'kode_klpdi' => 'D53', 'kode_provinsi' => 7, 'nama_klpdi' => 'Kab. Bengkulu Utara']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16055, 'kode_klpdi' => 'D530', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kab. Padang Lawas Utara']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14662, 'kode_klpdi' => 'D531', 'kode_provinsi' => 2, 'nama_klpdi' => 'Kota Sibolga']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16063, 'kode_klpdi' => 'D532', 'kode_provinsi' => 24, 'nama_klpdi' => 'Kab. Bolaang Mongondow Selatan']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 14904, 'kode_klpdi' => 'D533', 'kode_provinsi' => 34, 'nama_klpdi' => 'Provinsi Kalimantan Utara']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16065, 'kode_klpdi' => 'D534', 'kode_provinsi' => 23, 'nama_klpdi' => 'Kab. Mahakam Ulu']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16064, 'kode_klpdi' => 'D535', 'kode_provinsi' => 19, 'nama_klpdi' => 'Kab. Malaka']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16066, 'kode_klpdi' => 'D536', 'kode_provinsi' => 12, 'nama_klpdi' => 'Kab. Pangandaran']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 27002, 'kode_klpdi' => 'D537', 'kode_provinsi' => 27, 'nama_klpdi' => 'Kab. Kolaka Timur']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 27003, 'kode_klpdi' => 'D538', 'kode_provinsi' => 27, 'nama_klpdi' => 'Kab. Konawe Kepulauan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 27005, 'kode_klpdi' => 'D539', 'kode_provinsi' => 8, 'nama_klpdi' => 'Kab. Pesisir Barat']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14730, 'kode_klpdi' => 'D54', 'kode_provinsi' => 7, 'nama_klpdi' => 'Kab. Lebong']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16067, 'kode_klpdi' => 'D540', 'kode_provinsi' => 6, 'nama_klpdi' => 'Kab. Musi Rawas Utara']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 27006, 'kode_klpdi' => 'D541', 'kode_provinsi' => 25, 'nama_klpdi' => 'Kab. Morowali Utara']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16061, 'kode_klpdi' => 'D542', 'kode_provinsi' => 31, 'nama_klpdi' => 'Kab. Pulau Morotai']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 268936, 'kode_klpdi' => 'D543', 'kode_provinsi' => 27, 'nama_klpdi' => 'Kab. Muna Barat']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15032, 'kode_klpdi' => 'D544', 'kode_provinsi' => 33, 'nama_klpdi' => 'Kab. Manokwari Selatan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16069, 'kode_klpdi' => 'D545', 'kode_provinsi' => 33, 'nama_klpdi' => 'Kab. Pegunungan Arfak']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16070, 'kode_klpdi' => 'D546', 'kode_provinsi' => 31, 'nama_klpdi' => 'Kab. Pulau Taliabu']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 268937, 'kode_klpdi' => 'D547', 'kode_provinsi' => 29, 'nama_klpdi' => 'Kab. Mamuju Tengah']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16110, 'kode_klpdi' => 'D548', 'kode_provinsi' => 27, 'nama_klpdi' => 'Kab. Buton Tengah']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16111, 'kode_klpdi' => 'D549', 'kode_provinsi' => 27, 'nama_klpdi' => 'Kab. Buton Selatan']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14737, 'kode_klpdi' => 'D55', 'kode_provinsi' => 7, 'nama_klpdi' => 'Kota Bengkulu']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 27007, 'kode_klpdi' => 'D550', 'kode_provinsi' => 32, 'nama_klpdi' => 'Kab. Nduga']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 27008, 'kode_klpdi' => 'D551', 'kode_provinsi' => 25, 'nama_klpdi' => 'Kab. Banggai Laut']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14868, 'kode_klpdi' => 'D552', 'kode_provinsi' => 20, 'nama_klpdi' => 'Kab. Mempawah']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14731, 'kode_klpdi' => 'D56', 'kode_provinsi' => 7, 'nama_klpdi' => 'Kab. Bengkulu Selatan']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14734, 'kode_klpdi' => 'D57', 'kode_provinsi' => 7, 'nama_klpdi' => 'Kab. Muko Muko']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14736, 'kode_klpdi' => 'D58', 'kode_provinsi' => 7, 'nama_klpdi' => 'Kab. Kepahiang']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14729, 'kode_klpdi' => 'D59', 'kode_provinsi' => 7, 'nama_klpdi' => 'Kab. Rejang Lebong']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14648, 'kode_klpdi' => 'D6', 'kode_provinsi' => 1, 'nama_klpdi' => 'Kab. Aceh Tengah']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16004, 'kode_klpdi' => 'D60', 'kode_provinsi' => 7, 'nama_klpdi' => 'Kab. Bengkulu Tengah']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14732, 'kode_klpdi' => 'D61', 'kode_provinsi' => 7, 'nama_klpdi' => 'Kab. Kaur']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14735, 'kode_klpdi' => 'D62', 'kode_provinsi' => 7, 'nama_klpdi' => 'Kab. Seluma']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 14815, 'kode_klpdi' => 'D63', 'kode_provinsi' => 14, 'nama_klpdi' => 'Provinsi DI Yogyakarta']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14815, 'kode_klpdi' => 'D64', 'kode_provinsi' => 14, 'nama_klpdi' => 'Kota Yogyakarta']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14816, 'kode_klpdi' => 'D65', 'kode_provinsi' => 14, 'nama_klpdi' => 'Kab. Gunungkidul']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14817, 'kode_klpdi' => 'D66', 'kode_provinsi' => 14, 'nama_klpdi' => 'Kab. Kulon Progo']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14814, 'kode_klpdi' => 'D67', 'kode_provinsi' => 14, 'nama_klpdi' => 'Kab. Sleman']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14818, 'kode_klpdi' => 'D68', 'kode_provinsi' => 14, 'nama_klpdi' => 'Kab. Bantul']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 14748, 'kode_klpdi' => 'D69', 'kode_provinsi' => 11, 'nama_klpdi' => 'Provinsi DKI Jakarta']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14636, 'kode_klpdi' => 'D7', 'kode_provinsi' => 1, 'nama_klpdi' => 'Kota Sabang']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 15052, 'kode_klpdi' => 'D76', 'kode_provinsi' => 28, 'nama_klpdi' => 'Provinsi Gorontalo']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15051, 'kode_klpdi' => 'D77', 'kode_provinsi' => 28, 'nama_klpdi' => 'Kab. Bone Bolango']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15053, 'kode_klpdi' => 'D78', 'kode_provinsi' => 28, 'nama_klpdi' => 'Kab. Pohuwato']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15054, 'kode_klpdi' => 'D79', 'kode_provinsi' => 28, 'nama_klpdi' => 'Kab. Boalemo']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14647, 'kode_klpdi' => 'D8', 'kode_provinsi' => 1, 'nama_klpdi' => 'Kab. Aceh Besar']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 16005, 'kode_klpdi' => 'D80', 'kode_provinsi' => 28, 'nama_klpdi' => 'Kab. Gorontalo Utara']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 15055, 'kode_klpdi' => 'D81', 'kode_provinsi' => 28, 'nama_klpdi' => 'Kab. Gorontalo']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 15052, 'kode_klpdi' => 'D82', 'kode_provinsi' => 28, 'nama_klpdi' => 'Kota Gorontalo']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 14707, 'kode_klpdi' => 'D83', 'kode_provinsi' => 5, 'nama_klpdi' => 'Provinsi Jambi']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14710, 'kode_klpdi' => 'D84', 'kode_provinsi' => 5, 'nama_klpdi' => 'Kab. Sarolangun']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14709, 'kode_klpdi' => 'D85', 'kode_provinsi' => 5, 'nama_klpdi' => 'Kab. Batanghari']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14706, 'kode_klpdi' => 'D86', 'kode_provinsi' => 5, 'nama_klpdi' => 'Kab. Kerinci']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14714, 'kode_klpdi' => 'D87', 'kode_provinsi' => 5, 'nama_klpdi' => 'Kab. Muaro Jambi']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14712, 'kode_klpdi' => 'D88', 'kode_provinsi' => 5, 'nama_klpdi' => 'Kab. Tanjung Jabung Barat']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14707, 'kode_klpdi' => 'D89', 'kode_provinsi' => 5, 'nama_klpdi' => 'Kota Jambi']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14630, 'kode_klpdi' => 'D9', 'kode_provinsi' => 1, 'nama_klpdi' => 'Kab. Aceh Jaya']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14711, 'kode_klpdi' => 'D90', 'kode_provinsi' => 5, 'nama_klpdi' => 'Kab. Merangin']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 16006, 'kode_klpdi' => 'D91', 'kode_provinsi' => 5, 'nama_klpdi' => 'Kota Sungai Penuh']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 27009, 'kode_klpdi' => 'D911', 'kode_provinsi' => 6, 'nama_klpdi' => 'Kab. Penukal Abab Lematang Ilir']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14708, 'kode_klpdi' => 'D92', 'kode_provinsi' => 5, 'nama_klpdi' => 'Kab. Tebo']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14713, 'kode_klpdi' => 'D93', 'kode_provinsi' => 5, 'nama_klpdi' => 'Kab. Tanjung Jabung Timur']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14705, 'kode_klpdi' => 'D94', 'kode_provinsi' => 5, 'nama_klpdi' => 'Kab. Bungo']);
        Klpdi::create(['jenis_klpdi' => 'PROVINSI', 'kode_kabupaten' => 14765, 'kode_klpdi' => 'D95', 'kode_provinsi' => 12, 'nama_klpdi' => 'Provinsi Jawa Barat']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14755, 'kode_klpdi' => 'D96', 'kode_provinsi' => 12, 'nama_klpdi' => 'Kab. Indramayu']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14776, 'kode_klpdi' => 'D97', 'kode_provinsi' => 12, 'nama_klpdi' => 'Kota Depok']);
        Klpdi::create(['jenis_klpdi' => 'KABUPATEN', 'kode_kabupaten' => 14769, 'kode_klpdi' => 'D98', 'kode_provinsi' => 12, 'nama_klpdi' => 'Kab. Karawang']);
        Klpdi::create(['jenis_klpdi' => 'KOTA', 'kode_kabupaten' => 14765, 'kode_klpdi' => 'D99', 'kode_provinsi' => 12, 'nama_klpdi' => 'Kota Bandung']);
        Klpdi::create(['jenis_klpdi' => 'LEMBAGA', 'kode_kabupaten' => 15064, 'kode_klpdi' => 'I100', 'kode_provinsi' => 10, 'nama_klpdi' => 'Badan Pengusahaan Kawasan Perdagangan Bebas Dan Pelabuhan Bebas Batam (984423)']);
        Klpdi::create(['jenis_klpdi' => 'LEMBAGA', 'kode_kabupaten' => 15064, 'kode_klpdi' => 'I81', 'kode_provinsi' => 10, 'nama_klpdi' => 'Badan Pengusahaan Kawasan Perdagangan Bebas Dan Pelabuhan Bebas Batam']);
        Klpdi::create(['jenis_klpdi' => 'LEMBAGA', 'kode_kabupaten' => 14636, 'kode_klpdi' => 'I82', 'kode_provinsi' => 1, 'nama_klpdi' => 'Badan Pengusahaan Kawasan Perdagangan Bebas Dan Pelabuhan Bebas Sabang']);
        Klpdi::create(['jenis_klpdi' => 'KEMENTERIAN', 'kode_kabupaten' => 14748, 'kode_klpdi' => 'K1', 'kode_provinsi' => 11, 'nama_klpdi' => 'Kementerian Agama']);
        Klpdi::create(['jenis_klpdi' => 'KEMENTERIAN', 'kode_kabupaten' => 14748, 'kode_klpdi' => 'K10', 'kode_provinsi' => 11, 'nama_klpdi' => 'Kementerian Keuangan']);
        Klpdi::create(['jenis_klpdi' => 'KEMENTERIAN', 'kode_kabupaten' => 14748, 'kode_klpdi' => 'K11', 'kode_provinsi' => 11, 'nama_klpdi' => 'Kementerian Komunikasi Dan Informatika']);
        Klpdi::create(['jenis_klpdi' => 'KEMENTERIAN', 'kode_kabupaten' => 14748, 'kode_klpdi' => 'K13', 'kode_provinsi' => 11, 'nama_klpdi' => 'Kementerian Koordinator Bidang Perekonomian']);
        Klpdi::create(['jenis_klpdi' => 'KEMENTERIAN', 'kode_kabupaten' => 14748, 'kode_klpdi' => 'K14', 'kode_provinsi' => 11, 'nama_klpdi' => 'Kementerian Koordinator Bidang Politik']);
    }
}
